@imprimir_HostAddress = http://localhost:5249

GET {{imprimir_HostAddress}}/imprimir
Accept: application/json

###

POST {{imprimir_HostAddress}}/imprimir
Content-Type: application/json
Accept: application/json

{
  "content": "FIRMEZA\n-------------------------\nCliente: Cliente de prueba\nProducto: Producto de prueba\nPrecio: $12.000\n-------------------------\nGracias por su compra\n"
}

###
